version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    hostname: "rabbitmq-master"
    expose:
      - "5672"
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  producer:
    build: ./producer
    container_name: producer
    ports:
      - "8080:8080"
    depends_on: 
      - rabbitmq

volumes:
  rabbitmq-data:
    external: false
